article/urls.py
from django.urls import path
from .views import (
        # ArticleFormView, 
        ArticleCreateModelView,
        ArticleCreateView,
        ArticleDeleteView,
        ArticleListView, 
        ArticleDetailView,
        ArticleUpdateModel,
        ArticleUpdateView
    )

app_name = 'article'
urlpatterns = [
    path('<int:page>', ArticleListView.as_view(), name='index'),
    path('detail/<slug:slug>',ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('create-model/', ArticleCreateModelView.as_view(), name='create-model'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('update-model/<int:pk>', ArticleUpdateModel.as_view(), name='update-model'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]
# pk = primary key (id)

blog/urls.py
from django.urls import path
from .views import (
        ListPostView, 
        FormPostView, 
        DeletePostView, 
        DetailPostView, 
    )

app_name = 'blog'
urlpatterns = [
    path('', ListPostView.as_view(), name='index'),
    path('create/',FormPostView.as_view(), name='create'),
    path('delete/<int:id_post>',DeletePostView.as_view(), name='delete'),
    path('update/<int:id_post>',FormPostView.as_view(mode='update'), name='update'),
    path('post/<slug:slug_post>/', DetailPostView.as_view(), name='detail'),
    
]

article/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.CharField(max_length=100)
    publish = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('article:detail', kwargs={'slug': self.slug})

    def __str__(self) :
        return f"{self.id}. {self.title}"

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','author']
        widgets = {
            'title' : forms.TextInput(
                attrs={
                    'class' : 'form-control col-sm-6',
                    'placeholder': 'Title Article...'
                }
            ),
            'content' : forms.Textarea(
                attrs={
                    'class' : 'form-control col-sm-6',
                    'placeholder': 'Content Article...'
                }
            ),
            'author' : forms.TextInput(
                attrs={
                    'class' : 'form-control col-sm-6',
                    'placeholder': 'Author Article...'
                }
            ),
        }

article/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, 
    DetailView, 
    # FormView, 
    CreateView,
    UpdateView,
    DeleteView
    )
from .models import Article
from .forms import ArticleForm

# Create your views here.
class ArticleListView(ListView):
    model = Article
    # order
    ordering = ['publish']
    # pagination
    paginate_by = 4
    # memberi context
    extra_context = {
        'title' : 'Article | Kelas Terbuka',
        'heading' : "Article",
        'subheading' : 'Article on Kelas Terbuka',
    }

class ArticleDetailView(DetailView):
    model = Article
    extra_context = {
        'title' : 'Detail Article | Kelas Terbuka',
        'heading' : "Detail Article",
        'subheading' : 'Detail Article on Kelas Terbuka',
    }

    def get_context_data(self, **kwargs):
        other_articles = self.model.objects.exclude(slug = self.kwargs['slug'])
        self.extra_context['other_articles'] = other_articles
        return super().get_context_data(**kwargs)

""" class ArticleFormView(FormView):
    form_class = ArticleForm
    template_name = 'article/article_create.html'
    # redirect url if success
    success_url = reverse_lazy('article:index', kwargs={'page':1})
    extra_context = {
        'title' : 'Create Article | Kelas Terbuka',
        'heading' : "Create Article",
        'subheading' : 'Create Article on Kelas Terbuka',
    }

    def form_valid(self, form) :
        form.save()
        return super().form_valid(form) """

# create view menggunakan FormMixin
class ArticleCreateView(CreateView):
    form_class = ArticleForm
    template_name = 'article/article_create.html'
    extra_context = {
        'title' : 'Create Article | Kelas Terbuka',
        'heading' : "Create Article",
        'subheading' : 'Create Article on Kelas Terbuka',
    }

# create view menggunakan ModelFormMixin
class ArticleCreateModelView(CreateView):
    model = Article
    fields = [
        'title',
        'content',
        'author'
    ]
    extra_context = {
        'title' : 'Create Article Model | Kelas Terbuka',
        'heading' : "Create Article Model",
        'subheading' : 'Create Article Model on Kelas Terbuka',
    }
    # karena menggunakan model maka template yang digunakan article_form, suffix _form

class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article/article_create.html'

class ArticleUpdateModel(UpdateView):
    model = Article
    fields = [
        'title',
        'content'
    ]

class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('article:index', kwargs={'page':1})

article/templates/article/article_confirm_delete.html
{% extends 'base.html' %} {% block content-1 %}
<h1>You Sure To Delete <b>"{{object.title}}" ?? </b></h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Yes" class="btn btn-danger" />
  <a href="{% url 'article:index' 1 %}">
    <input type="button" value="No" class="btn btn-outline-primary" />
  </a>
</form>
{% endblock content-1 %}

article/templates/article/article_create.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
    <div class="row" style="height: 100%;" >
        <div class="col self-center">
            <form method="post">
                {% csrf_token %}
                {% for input in form %}
                    <div class="form-group">
                        {{input.label}}
                        {{input}}
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content-1 %}

article/templates/article/article_detail.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
    <div class="row my-5">
        <div class="col">
        <a href="{% url 'article:index' 1 %}" class="btn btn-primary">Back</a>
        <h1>{{object.title}}</h1>
        <span class="text-muted">Author : {{object.author}} </span>
        <br>
        <span class="text-muted">Publish : {{object.publish}} </span>
        <br>
        <span class="text-muted">Update : {{object.update}} </span>
        <br>
        <br>
        <p>
            {{object.content}}
        </p>
        <br>
        <br>
        <a href="{% url 'article:update' object.pk %}" class="btn btn-outline-info">Update1</a>
        <a href="{% url 'article:update-model' object.pk %}" class="btn btn-outline-info">Update2</a>
        <a href="{% url 'article:delete' object.pk %}" class="btn btn-danger">Delete</a>
        <hr>
        <br>
        <h3>Other Articles</h3>
        <ol>
            {% for article in other_articles %}
              <li>
                <a href="{% url 'article:detail' article.slug %}">
                  {{article.title}} ~ {{article.author}} | {{article.publish}}
                </a>
              </li>
            {% endfor %}
          </ol>
    </div>
{% endblock content-1 %}

article/templates/article/article_form.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
    <div class="row" style="height: 100%;" >
        <div class="col self-center">
            <form method="post">
                {% csrf_token %}
                {% for input in form %}
                    <div class="form-group">
                        {{input.label}}
                        {{input}}
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content-1 %}

article/templates/article/article_list.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
  <div class="row">
    <div class="col">
      <a href="{% url 'article:create' %}" class="btn btn-outline-primary">+ Create Article</a>
    </div>
  </div>
  <div class="row mt-4">
        <ol>
          {% for article in object_list %}
            <li>
              <a href="{% url 'article:detail' article.slug %}">
                {{article.title}} ~ {{article.author}} | {{article.publish}}
              </a>
            </li>
          {% endfor %}
        </ol>
  </div>

  <!-- nav pagination -->
  <nav>
    <ul class="pagination">
    {% if is_paginated %}
          <li class="page-item">
            {% if page_obj.has_previous %}
              <a class="page-link" href="{% url 'article:index' page_obj.previous_page_number %}">&laquo;</a>
            {% else %}
              <span class="disabled page-link text-muted">&laquo;</span>
            {% endif %}
          </li>

          {% for page_num in paginator.page_range %}
          <li class="page-item">
              <a class="page-link" href="{% url 'article:index' page_num %}">
                {{page_num}}
              </a>
            </li>
            {% endfor %}

          <li class="page-item">
            {% if page_obj.has_next %}
              <a class="page-link" href="{% url 'article:index' page_obj.next_page_number %}">&raquo;</a>
            {% else %}
              <span class="disabled page-link text-muted">&raquo;</span>
            {% endif %}
          </li>
    {% endif %}
    </ul>
  </nav>
{% endblock content-1 %}