article/urls.py
from django.urls import path
from .views import (
        # ArticleFormView, 
        ArticleCreateModelView,
        ArticleCreateView,
        ArticleDeleteView,
        ArticleListView, 
        ArticleDetailView,
        ArticleUpdateModel,
        ArticleUpdateView
    )

app_name = 'article'
urlpatterns = [
    path('<int:page>', ArticleListView.as_view(), name='index'),
    path('detail/<slug:slug>',ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('create-model/', ArticleCreateModelView.as_view(), name='create-model'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('update-model/<int:pk>', ArticleUpdateModel.as_view(), name='update-model'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]
# pk = primary key (id)

blog/urls.py
from django.urls import path
from .views import (
        ListPostView, 
        FormPostView, 
        DeletePostView, 
        DetailPostView, 
    )

app_name = 'blog'
urlpatterns = [
    path('', ListPostView.as_view(), name='index'),
    path('create/',FormPostView.as_view(), name='create'),
    path('delete/<int:id_post>',DeletePostView.as_view(), name='delete'),
    path('update/<int:id_post>',FormPostView.as_view(mode='update'), name='update'),
    path('post/<slug:slug_post>/', DetailPostView.as_view(), name='detail'),
    
]

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from .validators import validate_title

# Create your models here.
class Post(models.Model):
    LIST_CATEGORY=(
        ('blog','Blog'),
        ('jurnal', 'Jurnal')
    )
    
    title = models.CharField(
            max_length=255, 
            validators=[validate_title]
        )
    body = models.TextField()
    category = models.CharField(
            max_length=50, 
            default='blog', 
            choices=LIST_CATEGORY
        )
    publish = models.DateTimeField(
            auto_now_add=True
        )
    update = models.DateTimeField(
            auto_now= True
        )
    slug = models.SlugField(
            blank=True, 
            editable=False
        )

    def save(self, *args, **kwargs):
        # create slug from title
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self) :
        return f"{self.id}. {self.title}"

blog/forms.py
from django import forms

""" class PostForm(forms.Form):
    CATEGORY = (
        ('blog', 'Blog'),
        ('jurnal', 'Jurnal')
    )
    title = forms.CharField(
            max_length=255, 
            widget=forms.TextInput(
                attrs={
                    'class' : 'form-control col-sm-6'
                }
            )
        )
    body = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class' : 'form-control col-sm-6'
                }
            )
        )
    category = forms.ChoiceField(choices=CATEGORY, 
        widget=forms.Select(
            attrs={
                'class' : 'form-control col-sm-6'
            }
    ))

    # validation
    def clean_title(self):
        title_input = self.cleaned_data.get('title')
        
        if title_input == 'Hello World' :
            raise forms.ValidationError("Judul telah ada di model")
        
        return title_input """

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'body',
            'category'
        ]
        widgets={
            'title' : forms.TextInput(
                attrs={
                    'class' : 'form-control col-sm-6',
                    'placeholder' : 'Input Title Post...'
                }
            ),

            'body' : forms.Textarea(
                attrs={
                    'class' : 'form-control col-sm-6',
                    'placeholder' : 'Input Body Post...'
                }
            ),

            'category' : forms.Select(
                attrs={
                    'class' : 'form-control col-sm-6',
                }
            ),
        }

blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.base import TemplateView, RedirectView
from .models import Post 
from .forms import PostForm

# Create your views here.
class FilterListView:
    def get_list_data(self, get_request):
        if len(get_request) == 0:
            filter_data = Post.objects.all()
        elif get_request.__contains__('post_category'):
            filter_data = Post.objects.filter(category = get_request['post_category'])
        else:
            filter_data = Post.objects.none()
        return filter_data

class ListPostView(FilterListView, TemplateView):
    template_name = 'blog/index.html'
    context = {
            "app_css" : 'blog/css/styles.css',
            'title' : 'Blog | Kelas Terbuka',
            'heading' : "Blog",
            'subheading' : 'Blog on Kelas Terbuka',
        }

    def get_context_data(self,*args,**kwargs):
        # posts = Post.objects.all()
        posts = self.get_list_data(self.request.GET)
        categories = Post.objects.values_list('category', flat=True).distinct()
        
        self.context['Posts'] = posts
        self.context['Categories'] = categories

        return self.context

class DeletePostView(RedirectView):
    pattern_name = 'blog:index'
    
    def get_redirect_url(self, *args, **kwargs):
        Post.objects.filter(id = kwargs['id_post']).delete()
        return super().get_redirect_url()

class DetailPostView(TemplateView):
    template_name = 'blog/detail.html'
    context = {
        'app_css' : 'blog/css/styles/css',
        'title' : 'Blog'
    }

    def get_context_data(self, *args, **kwargs):
        post = Post.objects.get(slug = kwargs['slug_post'])
        self.context['Post'] = post

        return self.context

class FormPostView(View):
    template_name = 'blog/create.html'
    form = PostForm()
    mode = None
    context = {
        "app_css" : 'blog/css/styles.css',
        'title' : 'Create Blog | Kelas Terbuka',
        'heading' : "Create Blog",
        'subheading' : 'Create Blog on Kelas Terbuka',
        'post_form' : form
    }

    def get(self, *args, **kwargs):
        # check mode
        if self.mode == 'update':
            update_post = Post.objects.get(id = kwargs['id_post'])
            data_post = update_post.__dict__
            self.form = PostForm(initial = data_post, instance = update_post)

            self.context = {
                'title' : 'Update Blog | Kelas Terbuka',
                'heading' : "Update Blog",
                'subheading' : 'Update Blog on Kelas Terbuka',
                'post_form' : self.form
            }
        return render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if kwargs.__contains__('id_post'):
            # update
            update_post = Post.objects.get(id = kwargs['id_post'])
            self.form = PostForm(self.request.POST, instance = update_post)
        else :
            # create
            self.form = PostForm(self.request.POST)

        if self.form.is_valid():
            self.form.save()
        
        return redirect('blog:index')

blog/templates/blog/article_list.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
  <div class="row">
        <ol>
          {% for article in object_list %}
            <li>
                {{article.title}} ~ {{article.author}} | {{article.publish}}
            </li>
          {% endfor %}
        </ol>
  </div>

  
  <nav>
    <ul class="pagination">
    {% if is_paginated %}
          <li class="page-item">
            {% if page_obj.has_previous %}
              <a class="page-link" href="{% url 'blog:article' page_obj.previous_page_number %}">&laquo;</a>
            {% else %}
              <span class="disabled page-link text-muted">&laquo;</span>
            {% endif %}
          </li>

          {% for page_num in paginator.page_range %}
          <li class="page-item">
              <a class="page-link" href="{% url 'blog:article' page_num %}">
                {{page_num}}
              </a>
            </li>
            {% endfor %}

          <li class="page-item">
            {% if page_obj.has_next %}
              <a class="page-link" href="{% url 'blog:article' page_obj.next_page_number %}">&raquo;</a>
            {% else %}
              <span class="disabled page-link text-muted">&raquo;</span>
            {% endif %}
          </li>
    {% endif %}
    </ul>
  </nav>
    

{% endblock content-1 %}

blog/templates/blog/category.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block content-1 %}
    <div class="row">
        <div class="col">
            <h1>Other Category</h1>
            <a href="/blog/" class="badge badge-primary"> All-post </a>
            {% for dataCategory in Categories %}
            <a href="/blog/category/{{dataCategory.category}}" class="badge badge-primary"> {{dataCategory.category}} </a>
            {% endfor %}
        </div>
    </div>

    {% for post in Posts %}
        <div class="row my-5">
        <div class="col">
            <a href="/blog/post/{{post.slug}}" class="link-detail-post h1">
            {{post.title}}
            </a>
            <!-- truncatechars = menampilkan beberapa char sesuai nilai yang ditentukan -->
            <p> {{post.body | truncatechars:200}} </p>
            <p> {{post.publish}} </p>
        </div>
        </div>
    {% endfor %}

{% endblock content-1 %}

blog/templates/blog/create.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}
    <div class="row" style="height: 100%;" >
        <div class="col self-center">
            <form method="post">
                {% csrf_token %}
                <!-- <div class="form-group">
                    {{error.title}}
                    {{post_form.title.label_tag}}
                    {{post_form.title}}
                </div>
                <div class="form-group">
                    {{post_form.body.label_tag}}
                    {{post_form.body}}
                </div>
                <div class="form-group">
                    {{post_form.category.label_tag}}
                    {{post_form.category}}
                </div> -->
                
                <!-- form with ModelForm -->
                {% for form in post_form %}
                    <div class="form-group">
                        {{form.label}}
                        {{form}}
                    </div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content-1 %}

blog/templates/blog/detail.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block content-1 %}
    <div class="row my-5">
      <div class="col">
        <h1>{{Post.title}}</h1>
        <span class="badge badge-pill badge-primary">{{Post.category}}</span>
        <br>
        <span class="text-muted"> Publish at : {{Post.publish}} </span>
        <br>
        <span class="text-muted"> Update at : {{Post.update}} </span>
        <br>
        <br>
        <p> {{Post.body}} </p>
        <div class="col">
          <a href="{% url 'blog:delete' Post.id %}" onclick="confirm('Apakah Anda Yakin Ingin Menghapust Postingan ini??')" class="btn btn-danger">Delete Post</a>
          <a href="{% url 'blog:update' Post.id %}" class="btn btn-warning">Update</a>
        </div>
      </div>
    </div>
{% endblock content-1 %}

blog/templates/blog/index.html
{% extends 'base.html' %} 
{% load static %}

{% block app_css %}
<link rel="stylesheet" href="{% static 'blog/css/styles.css'%}" />
{% endblock app_css %}

{% block header %}
<h1 class="display-4 text-left" style="margin-top: 100px;">{{heading}}</h1>
<p class="lead text-left">~ {{subheading}}</p>
{% endblock header %}

{% block content-1 %}

  <div class="row">
    <div class="col">
      <h1>Blog By Category</h1>
      <a href="{% url 'blog:index' %}" class="badge badge-primary"> All-post </a>
      {% for category in Categories %}
      <a href="{% url 'blog:index' %}?post_category={{category}}" class="badge badge-primary"> {{category}} </a>
      {% endfor %}
    </div>
    <div class="col mt-2">
      <a href="{% url 'blog:create' %}" class="badge badge-secondary float-right">+ Create Post</a>
    </div>
  </div>

  {% for post in Posts %}
    <div class="row my-5">
      <div class="col">
        <a href="{% url 'blog:detail' slug_post=post.slug %}" class="link-detail-post h1">
          {{post.title}}
        </a>
        <p> {{post.body | truncatechars:200}} <a href="{% url 'blog:detail' slug_post=post.slug %}">read more</a> </p>
        <p> {{post.publish}} </p>
      </div>
    </div>
  {% endfor %}

{% endblock content-1 %}