about/urls.py
from django.urls import path
from . import views

app_name="about"
urlpatterns = [
    path('', views.index, name='index')
]

blog/urls.py
from django.urls import path
from .views import (
        ListPostView, 
        FormPostView, 
        DeletePostView, 
        DetailPostView, 
    )

app_name = 'blog'
urlpatterns = [
    path('', ListPostView.as_view(), name='index'),
    path('create/',FormPostView.as_view(), name='create'),
    path('delete/<int:id_post>',DeletePostView.as_view(), name='delete'),
    path('update/<int:id_post>',FormPostView.as_view(mode='update'), name='update'),
    path('post/<slug:slug_post>/', DetailPostView.as_view(), name='detail'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('article/', include('article.urls', namespace = 'article')),
    path('about/', include('about.urls', namespace = 'about')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('sosmed/', include('sosmed.urls', namespace = 'sosmed'))
]

templates/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top navbar-dark" id="myNav">
  <a class="navbar-brand" href="#">
    <img
      height="30px"
      class="logo"
      src="{% static 'img/logo.png'%}"
      alt="logo"
    />
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:index' 1 %}">Article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about:index' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact:index' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sosmed:index' %}">Sosmed</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
    </ul>
  </div>
</nav>

templates/snippets/scripts.html
{% load static %}

<script src="{% static 'vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'vendor/popper/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/snippets/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css'%}" />