blog/urls.py
from django.urls import path
from .views import (
        ListPostView, 
        FormPostView, 
        DeletePostView, 
        DetailPostView, 
    )

app_name = 'blog'
urlpatterns = [
    path('', ListPostView.as_view(), name='index'),
    path('create/',FormPostView.as_view(), name='create'),
    path('delete/<int:id_post>',DeletePostView.as_view(), name='delete'),
    path('update/<int:id_post>',FormPostView.as_view(mode='update'), name='update'),
    path('post/<slug:slug_post>/', DetailPostView.as_view(), name='detail'),
    
]

sosmed/urls.py
from django.urls import path
from .views import ListView, DeleteView, SosmedFormView

app_name = 'sosmed'
urlpatterns = [
    path('', ListView.as_view(), name='index'),
    path('create/', SosmedFormView.as_view(), name='create'),
    path('update/<int:update_id>', SosmedFormView.as_view(mode='update'), name='update'),
    path('delete/<int:delete_id>', DeleteView.as_view(), name='delete'),
]

sosmed/models.py
from django.db import models

# Create your models here.
class Sosmed(models.Model) :
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    username = models.CharField(max_length=30)
    content = models.CharField(max_length=30)

    def __str__(self) :
        return f"{self.id}. {self.username}"

sosmed/forms.py
from django import forms
from .models import Sosmed

class SosmedForm(forms.ModelForm):
    class Meta:
        model = Sosmed
        fields = [
            'first_name',
            'last_name',
            'username',
            'content'
        ]

sosmed/views.py
from django.views import View
from django.views.generic.base import TemplateView, RedirectView
from .models import Sosmed
from .forms import SosmedForm
from django.shortcuts import render, redirect

# Create your views here.

# filter handler
class FilterListView:
    def get_list_data(self, get_request):
        if len(get_request) == 0:
            filter_data = Sosmed.objects.all()
        elif get_request.__contains__('user_content'):
            filter_data = Sosmed.objects.filter(content = get_request['user_content'])
        else:
            filter_data = Sosmed.objects.none()
        return filter_data

        
class ListView(FilterListView, TemplateView):
    template_name = 'sosmed/index.html'

    def get_context_data(self, **kwargs) :
        sosmeds = self.get_list_data(self.request.GET)
        list_contents = Sosmed.objects.values_list('content', flat=True).distinct()

        context = {
            'title' : 'Sosmed | Kelas Terbuka',
            'heading' : 'Social Media',
            'sosmeds' : sosmeds,
            'list_contents' : list_contents
        }

        return context

class DeleteView(RedirectView) :
    pattern_name = 'sosmed:index'

    def get_redirect_url(self, *args, **kwargs):
        Sosmed.objects.filter(id=kwargs['delete_id']).delete() 
        return super().get_redirect_url()

class SosmedFormView(View):
    template_name = 'sosmed/create.html'
    form = SosmedForm()
    mode = None
    context = {
        'title' : 'Tambah Akun',
        'sosmed_form' : form
        }

    def get(self, *args, **kwargs):
        # mode = update
        if self.mode == 'update':
            # get sosmed by id
            sosmed_update = Sosmed.objects.get(id = kwargs['update_id'])
            # get data sosmed
            data = sosmed_update.__dict__
            # form for update
            self.form = SosmedForm(initial=data, instance=sosmed_update)
            # context for update
            self.context = {
                'title' : 'Update Akun',
                'sosmed_form' : self.form
            }
        return render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if kwargs.__contains__('update_id'):
            # update
            sosmed_update = Sosmed.objects.get(id = kwargs['update_id'])
            self.form = SosmedForm(self.request.POST, instance=sosmed_update)
        else:
            # create
            self.form = SosmedForm(self.request.POST)
        
        if self.form.is_valid():
            self.form.save()

        return redirect('sosmed:index')

sosmed/templates/sosmed/create.html
{% extends 'base.html' %}

{% block content-1 %}
	<h1>{{title}}</h1>
	<form method="POST">
		{% csrf_token %}
		<table>
			{{sosmed_form.as_table}}
		</table>
		<button type="Submit">Kirim</button>
	</form>
{% endblock content-1 %}

sosmed/templates/sosmed/index.html
{% extends 'base.html' %}

{% block header %}
<h1 class="display-4">{{ heading }}</h1>
{% endblock header %} 

{% block content-1 %}
  <div class="row" style="height: 100%">
    <a href="{% url 'sosmed:create' %}" class="btn btn-primary p-6">Add</a>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">No.</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Username</th>
            <th scope="col">Content</th>
            <th scope="col">Delete</th>
            <th scope="col">Update</th>
          </tr>
        </thead>
        <tbody>
            {% for akun in sosmeds %} 
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{akun.first_name}}</td>
                <td>{{akun.last_name}}</td>
                <td>{{akun.username}}</td>
                <td>{{akun.content}}</td>
                <td><a href="{% url 'sosmed:delete' akun.id %}" class="btn btn-danger">Delete</a></td>
                <td><a href="{% url 'sosmed:update' akun.id %}" class="btn btn-outline-warning">Update</a></td>
            </tr>
            {% endfor %}
        </tbody>    
    </table>
    <h3>Filter By Content : </h3>
    {% for content in list_contents %}
    <a href="{% url 'sosmed:index' %}?user_content={{content}}" class="badge badge-info m-2 px-4">{{content}}</a>
    {% endfor %}
    <a href="{% url 'sosmed:index' %}" class="badge badge-info m-2 px-4">All</a>
    
  </div>
{% endblock content-1 %}
  